version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-credentials:username
    DOCKERHUB_PASSWORD: dockerhub-credentials:password

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ImageName -f ./Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to Amazon ECR...
      - docker tag $ImageName:latest 850386665167.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest
      - docker push 850386665167.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest